import csv, sys, re
sys.stdout.reconfigure(encoding='utf-8')

# Product type keywords to strip from the end of product names
PRODUCT_TYPES = [
    'Sweater', 'T-shirt', 'T-Shirt', 'Shirt', 'Hoodie', 'Jacket', 'Coat',
    'Pants', 'Jeans', 'Shorts', 'Trouser', 'Track Pants', 'Sweatpants',
    'Sneakers', 'Shoes', 'Boots', 'Sandals', 'Slippers',
    'Watch', 'Watches',
    'Bag', 'Bags', 'Backpack', 'Belt', 'Hat', 'Cap', 'Sunglasses',
    'Scarf', 'Gloves', 'Socks', 'Underwear', 'Boxer',
    'Dress', 'Skirt', 'Vest', 'Polo', 'Cardigan', 'Blazer',
    'Windbreaker', 'Parka', 'Puffer', 'Fleece', 'Tank Top',
    'Joggers', 'Cargo', 'Chinos', 'Leggings',
    'Loafers', 'Mules', 'Derby', 'Oxford', 'Chelsea',
    'Slides', 'Clogs', 'Espadrilles',
    'Bracelet', 'Necklace', 'Ring', 'Earrings',
    'Wallet', 'Pouch', 'Tote', 'Crossbody', 'Clutch',
    'Beanie', 'Bucket Hat', 'Fedora',
    'Bikini', 'Swim Shorts', 'Swim Trunks',
    'Robe', 'Pajamas', 'Loungewear',
    'Apron', 'Towel', 'Blanket', 'Pillow',
    'Candle', 'Diffuser', 'Soap', 'Lotion',
    'Mug', 'Plate', 'Bowl', 'Cup',
    'Notebook', 'Pen', 'Sticker', 'Keychain',
    'Phone Case', 'AirPods Case',
    'Tote Bag', 'Shoulder Bag', 'Messenger Bag',
    'Eyeglasses',
    'Snapback', 'Dad Hat',
    'Bandana', 'Headband',
    'Umbrella',
    'Water Bottle', 'Tumbler',
    'Yoga Mat', 'Resistance Band',
    'Shopper',
    'Slip-On', 'High-Top', 'Low-Top', 'Mid-Top',
    'Runner', 'Trainer', 'Court', 'Skate',
    'Moccasin', 'Brogue', 'Monk Strap',
    'Sandal', 'Flip Flop',
    'Boot', 'Combat Boot', 'Hiking Boot', 'Rain Boot',
    'Polo Shirt', 'Rugby Shirt', 'Henley',
    'Bomber Jacket', 'Denim Jacket', 'Leather Jacket', 'Varsity Jacket',
    'Trench Coat', 'Overcoat', 'Peacoat', 'Duffle Coat',
    'Anorak', 'Gilet', 'Bodywarmer',
    'Crop Top', 'Tube Top', 'Camisole', 'Bralette',
    'Maxi Dress', 'Mini Dress', 'Midi Dress', 'Shirt Dress',
    'Pencil Skirt', 'A-Line Skirt', 'Pleated Skirt',
    'Chino Shorts', 'Denim Shorts', 'Bermuda Shorts',
    'Jumpsuit', 'Romper', 'Onesie',
    'Thermal', 'Long Sleeve', 'Short Sleeve',
    'Graphic Tee', 'Oversized Tee', 'Fitted Tee',
    'Crewneck', 'Quarter Zip', 'Full Zip',
    'Pullover', 'Zip-Up',
    'Track Jacket', 'Tracksuit',
    'Swimwear', 'Board Shorts',
    'Linen Shirt', 'Flannel Shirt', 'Oxford Shirt', 'Chambray Shirt',
    'Denim Shirt', 'Silk Shirt', 'Satin Shirt',
    'Cashmere Sweater', 'Wool Sweater', 'Cotton Sweater',
    'Knit Sweater', 'Cable Knit', 'Turtleneck', 'Mock Neck',
    'V-Neck', 'Crew Neck', 'Boat Neck',
    'Hooded Sweatshirt', 'Crewneck Sweatshirt',
    'Fleece Hoodie', 'French Terry Hoodie',
    'Denim Jeans', 'Skinny Jeans', 'Straight Jeans', 'Slim Jeans',
    'Relaxed Jeans', 'Tapered Jeans', 'Wide-Leg Jeans',
    'Bootcut Jeans', 'Flare Jeans', 'Cropped Jeans',
    'Ripped Jeans', 'Distressed Jeans', 'Raw Denim',
    'Cargo Pants', 'Wide Pants', 'Straight Pants', 'Slim Pants',
    'Tailored Pants', 'Dress Pants', 'Suit Pants',
    'Pleated Pants', 'Drawstring Pants', 'Elastic Waist Pants',
    'Linen Pants', 'Cotton Pants', 'Wool Pants',
    'Nylon Pants', 'Technical Pants', 'Utility Pants',
    'Jogger Pants',
    'Running Shoes', 'Basketball Shoes', 'Tennis Shoes',
    'Football Boots', 'Soccer Cleats', 'Golf Shoes',
    'Hiking Shoes', 'Trail Shoes', 'Walking Shoes',
    'Dress Shoes', 'Formal Shoes', 'Casual Shoes',
    'Leather Shoes', 'Suede Shoes', 'Canvas Shoes',
    'Knit Shoes', 'Mesh Shoes', 'Suede Sneakers',
    'Platform Shoes', 'Wedge Shoes', 'Heeled Shoes',
    'Flat Shoes', 'Ballet Flats', 'Mary Janes',
    'Ankle Boots', 'Knee-High Boots', 'Thigh-High Boots',
    'Chelsea Boots', 'Chukka Boots', 'Desert Boots',
    'Work Boots', 'Steel Toe Boots',
    'Snow Boots', 'Winter Boots',
    'Sport Watch', 'Dress Watch', 'Dive Watch',
    'Chronograph Watch', 'Automatic Watch', 'Quartz Watch',
    'Smart Watch', 'Digital Watch', 'Analog Watch',
    'Pocket Watch', 'Field Watch', 'Pilot Watch',
    'Leather Strap Watch', 'Metal Strap Watch', 'NATO Strap Watch',
    'Gold Watch', 'Silver Watch', 'Rose Gold Watch',
    'Titanium Watch', 'Ceramic Watch',
    'Luxury Watch', 'Fashion Watch', 'Vintage Watch',
    'Reading Glasses', 'Blue Light Glasses',
    'Aviator Sunglasses', 'Wayfarer Sunglasses', 'Round Sunglasses',
    'Cat Eye Sunglasses', 'Oversized Sunglasses', 'Sport Sunglasses',
    'Polarized Sunglasses', 'Mirrored Sunglasses',
    'Leather Belt', 'Canvas Belt', 'Woven Belt',
    'Reversible Belt', 'Braided Belt', 'Chain Belt',
    'Wool Scarf', 'Silk Scarf', 'Cashmere Scarf',
    'Infinity Scarf', 'Bandana Scarf', 'Pashmina',
    'Leather Gloves', 'Wool Gloves', 'Touchscreen Gloves',
    'Driving Gloves', 'Ski Gloves',
    'Wool Socks', 'Cotton Socks', 'Athletic Socks',
    'Ankle Socks', 'Knee-High Socks', 'Compression Socks',
    'Silk Underwear', 'Cotton Underwear', 'Modal Underwear',
    'Boxer Briefs', 'Briefs', 'Trunks',
    'Sports Bra', 'Bra',
    'Slip', 'Chemise',
    'Thermal Underwear', 'Base Layer',
    'Rain Jacket', 'Wind Jacket', 'Softshell Jacket',
    'Hardshell Jacket', 'Insulated Jacket', 'Lightweight Jacket',
    'Quilted Jacket', 'Padded Jacket', 'Stadium Jacket',
    'Coach Jacket', 'Work Jacket', 'Field Jacket',
    'Military Jacket', 'Safari Jacket', 'Fishing Jacket',
    'Down Jacket', 'Puffer Jacket', 'Down Vest',
    'Fleece Jacket', 'Sherpa Jacket', 'Teddy Jacket',
    'Denim Vest', 'Puffer Vest', 'Quilted Vest',
    'Suit Jacket', 'Sport Coat',
    'Tuxedo', 'Dinner Jacket',
    'Linen Blazer', 'Wool Blazer', 'Cotton Blazer',
    'Unstructured Blazer', 'Double-Breasted Blazer',
    'Single-Breasted Blazer',
    'Tee', 'Top',
    'Tank', 'Singlet', 'Muscle Tee',
    'Ringer Tee', 'Pocket Tee', 'Longline Tee',
    'Boxy Tee', 'Cropped Tee',
    'Polo',
    'Button-Down', 'Button-Up', 'Dress Shirt',
    'Casual Shirt', 'Print Shirt', 'Pattern Shirt',
    'Striped Shirt', 'Checked Shirt', 'Plaid Shirt',
    'Floral Shirt', 'Tropical Shirt', 'Aloha Shirt',
    'Cuban Collar Shirt', 'Camp Collar Shirt',
    'Mandarin Collar Shirt', 'Band Collar Shirt',
    'Grandad Collar Shirt',
    'Henley Shirt', 'Grandad Shirt',
    'Work Shirt', 'Chore Shirt', 'Utility Shirt',
    'Western Shirt', 'Cowboy Shirt',
    'Bowling Shirt', 'Guayabera',
    'Guernsey', 'Fisherman Sweater', 'Aran Sweater',
    'Fair Isle Sweater', 'Intarsia Sweater',
    'Argyle Sweater', 'Striped Sweater',
    'Colorblock Sweater', 'Patchwork Sweater',
    'Embroidered Sweater', 'Printed Sweater',
    'Logo Sweater', 'Graphic Sweater',
    'Cropped Sweater', 'Oversized Sweater',
    'Fitted Sweater', 'Relaxed Sweater',
    'Lightweight Sweater', 'Heavyweight Sweater',
    'Summer Sweater', 'Winter Sweater',
    'Spring Jacket', 'Fall Jacket', 'Autumn Jacket',
    'Transitional Jacket', 'All-Season Jacket',
    'Reversible Jacket', 'Packable Jacket',
    'Waterproof Jacket', 'Water-Resistant Jacket',
    'Breathable Jacket', 'Ventilated Jacket',
    'Reflective Jacket', 'Hi-Vis Jacket',
    'Safety Jacket', 'High-Visibility Jacket',
    'Fire-Resistant Jacket', 'Flame-Retardant Jacket',
    'Anti-Static Jacket', 'ESD Jacket',
    'Cleanroom Jacket', 'Lab Coat',
    'Chef Coat', 'Chef Jacket',
    'Medical Scrub', 'Nurse Uniform',
    'School Uniform', 'Work Uniform',
    'Team Jersey', 'Sports Jersey', 'Football Jersey',
    'Basketball Jersey', 'Baseball Jersey', 'Hockey Jersey',
    'Racing Jersey', 'Cycling Jersey',
    'Compression Shirt', 'Performance Shirt',
    'Moisture-Wicking Shirt', 'Quick-Dry Shirt',
    'UV Protection Shirt', 'Sun Protection Shirt',
    'Cooling Shirt', 'Heated Shirt',
    'Smart Shirt', 'Tech Shirt',
    'Graphic T-Shirt', 'Logo T-Shirt', 'Band T-Shirt',
    'Vintage T-Shirt', 'Retro T-Shirt',
    'Tour T-Shirt', 'Concert T-Shirt',
    'Festival T-Shirt', 'Event T-Shirt',
    'Charity T-Shirt', 'Cause T-Shirt',
    'Slogan T-Shirt', 'Statement T-Shirt',
    'Minimalist T-Shirt', 'Plain T-Shirt',
    'Heavyweight T-Shirt', 'Lightweight T-Shirt',
    'Organic Cotton T-Shirt', 'Bamboo T-Shirt',
    'Hemp T-Shirt', 'Linen T-Shirt',
    'Silk T-Shirt', 'Cashmere T-Shirt',
    'Merino Wool T-Shirt', 'Alpaca T-Shirt',
    'Recycled T-Shirt', 'Sustainable T-Shirt',
    'Eco-Friendly T-Shirt', 'Green T-Shirt',
    'Limited Edition T-Shirt', 'Exclusive T-Shirt',
    'Collaboration T-Shirt', 'Capsule Collection T-Shirt',
    'Archive T-Shirt', 'Heritage T-Shirt',
    'Classic T-Shirt', 'Essential T-Shirt',
    'Staple T-Shirt', 'Basic T-Shirt',
    'Premium T-Shirt', 'Luxury T-Shirt',
    'Designer T-Shirt', 'High-End T-Shirt',
    'Streetwear T-Shirt', 'Urban T-Shirt',
    'Skate T-Shirt', 'Surf T-Shirt',
    'Snowboard T-Shirt', 'Ski T-Shirt',
    'Climbing T-Shirt', 'Hiking T-Shirt',
    'Fishing T-Shirt', 'Hunting T-Shirt',
    'Camping T-Shirt', 'Outdoor T-Shirt',
    'Travel T-Shirt', 'Adventure T-Shirt',
    'Expedition T-Shirt', 'Explorer T-Shirt',
    'Pioneer T-Shirt', 'Frontier T-Shirt',
    'Wilderness T-Shirt', 'Nature T-Shirt',
    'Mountain T-Shirt', 'Forest T-Shirt',
    'Ocean T-Shirt', 'Beach T-Shirt',
    'Desert T-Shirt', 'Jungle T-Shirt',
    'Arctic T-Shirt', 'Tropical T-Shirt',
    'Safari T-Shirt',
    'Scout T-Shirt', 'Ranger T-Shirt',
    'Trooper T-Shirt', 'Soldier T-Shirt',
    'Warrior T-Shirt', 'Knight T-Shirt',
    'Samurai T-Shirt', 'Ninja T-Shirt',
    'Pirate T-Shirt', 'Viking T-Shirt',
    'Gladiator T-Shirt', 'Spartan T-Shirt',
    'Roman T-Shirt', 'Greek T-Shirt',
    'Egyptian T-Shirt', 'Aztec T-Shirt',
    'Mayan T-Shirt', 'Inca T-Shirt',
    'Celtic T-Shirt', 'Norse T-Shirt',
    'Anglo T-Shirt', 'Saxon T-Shirt',
    'Norman T-Shirt', 'Medieval T-Shirt',
    'Renaissance T-Shirt', 'Baroque T-Shirt',
    'Gothic T-Shirt', 'Victorian T-Shirt',
    'Edwardian T-Shirt', 'Georgian T-Shirt',
    'Regency T-Shirt', 'Empire T-Shirt',
    'Art Deco T-Shirt', 'Art Nouveau T-Shirt',
    'Bauhaus T-Shirt', 'Modernist T-Shirt',
    'Postmodern T-Shirt', 'Contemporary T-Shirt',
    'Futuristic T-Shirt', 'Retro-Futuristic T-Shirt',
    'Steampunk T-Shirt', 'Cyberpunk T-Shirt',
    'Dieselpunk T-Shirt', 'Atompunk T-Shirt',
    'Biopunk T-Shirt', 'Solarpunk T-Shirt',
    'Lunarpunk T-Shirt',
    'Vaporwave T-Shirt', 'Synthwave T-Shirt',
    'Outrun T-Shirt', 'Retrowave T-Shirt',
    'Chillwave T-Shirt', 'Dreamwave T-Shirt',
    'Future Funk T-Shirt', 'Mallsoft T-Shirt',
    'Hardwave T-Shirt', 'Splitcore T-Shirt',
    'Breakcore T-Shirt', 'Drill T-Shirt',
    'Trap T-Shirt', 'Phonk T-Shirt',
    'Hyperpop T-Shirt', 'Digicore T-Shirt',
    'Glitchcore T-Shirt', 'Webcore T-Shirt',
    'Corecore T-Shirt', 'Weirdcore T-Shirt',
    'Dreamcore T-Shirt', 'Traumacore T-Shirt',
    'Nostalgiacore T-Shirt', 'Anemoiacore T-Shirt',
    'Kidcore T-Shirt', 'Tweencore T-Shirt',
    'Teencore T-Shirt', 'Youthcore T-Shirt',
    'Eldercore T-Shirt', 'Grandpacore T-Shirt',
    'Cottagecore T-Shirt', 'Farmcore T-Shirt',
    'Goblincore T-Shirt', 'Fairycore T-Shirt',
    'Dark Academia T-Shirt', 'Light Academia T-Shirt',
    'Royalcore T-Shirt', 'Princesscore T-Shirt',
    'Angelcore T-Shirt', 'Demoncore T-Shirt',
    'Vampirecore T-Shirt', 'Werewolfcore T-Shirt',
    'Zombiecore T-Shirt', 'Ghostcore T-Shirt',
    'Witchcore T-Shirt', 'Wizardcore T-Shirt',
    'Mermaidcore T-Shirt', 'Sirencore T-Shirt',
    'Piratecore T-Shirt', 'Nauticalcore T-Shirt',
    'Spacecore T-Shirt', 'Astrocore T-Shirt',
    'Galaxycore T-Shirt', 'Nebulacore T-Shirt',
    'Starcore T-Shirt', 'Mooncore T-Shirt',
    'Suncore T-Shirt', 'Planetcore T-Shirt',
    'Cometcore T-Shirt', 'Meteorcore T-Shirt',
    'UFOcore T-Shirt', 'Aliencore T-Shirt',
    'Robotcore T-Shirt', 'Androidcore T-Shirt',
    'Cyborgcore T-Shirt', 'Mechacore T-Shirt',
    'Dronecore T-Shirt', 'Satellitecore T-Shirt',
    'Rocketcore T-Shirt', 'Spaceshipcore T-Shirt',
    'Stationcore T-Shirt', 'Colonycore T-Shirt',
    'Terraformcore T-Shirt', 'Warpcore T-Shirt',
    'Hyperspacecore T-Shirt', 'Multiversecore T-Shirt',
    'Dimensioncore T-Shirt', 'Timetravelcore T-Shirt',
    'Paradoxcore T-Shirt', 'Quantumcore T-Shirt',
    'Stringcore T-Shirt', 'Particlecore T-Shirt',
    'Atomcore T-Shirt', 'Moleculecore T-Shirt',
    'Cellcore T-Shirt', 'Genecore T-Shirt',
    'DNACore T-Shirt', 'RNACore T-Shirt',
    'Proteincore T-Shirt', 'Enzymecore T-Shirt',
    'Hormonecore T-Shirt', 'Neurocore T-Shirt',
    'Synapsecor T-Shirt', 'Axoncore T-Shirt',
    'Dendritecore T-Shirt', 'Cortexcore T-Shirt',
    'Cerebellumcore T-Shirt', 'Brainstemcore T-Shirt',
    'Hippocampuscore T-Shirt', 'Amygdalacore T-Shirt',
    'Thalamuscore T-Shirt', 'Hypothalamuscore T-Shirt',
    'Pituitarycore T-Shirt', 'Pinealcore T-Shirt',
    'Corpuscallosumcore T-Shirt', 'Basalgangliacore T-Shirt',
    'Olfactorybulbcore T-Shirt', 'Opticnervecore T-Shirt',
    'Vagusnervecore T-Shirt', 'Sciaticnervecore T-Shirt',
    'Spinalcordcore T-Shirt', 'Peripheralnervecore T-Shirt',
    'Autonomicnervecore T-Shirt', 'Sympatheticnervecore T-Shirt',
    'Parasympatheticnervecore T-Shirt', 'Entericnervecore T-Shirt',
    'Somaticnervecore T-Shirt', 'Sensorynervecore T-Shirt',
    'Motornervecore T-Shirt', 'Mixednervecore T-Shirt',
    'Cranialnervecore T-Shirt', 'Spinalnervecore T-Shirt',
    'Dorsalrootganglioncore T-Shirt', 'Ventralrootcore T-Shirt',
    'Dorsalhorn T-Shirt', 'Ventralhorn T-Shirt',
    'Lateralhorn T-Shirt', 'Centralcanal T-Shirt',
    'Graymatter T-Shirt', 'Whitematter T-Shirt',
    'Cerebrospinalfluid T-Shirt', 'Meninges T-Shirt',
    'Duramater T-Shirt', 'Arachnoidmater T-Shirt',
    'Piamater T-Shirt', 'Subarachnoidspace T-Shirt',
    'Epiduralspace T-Shirt', 'Subduralspace T-Shirt',
    'Cerebralcortex T-Shirt', 'Cerebellarcortex T-Shirt',
    'Prefrontalcortex T-Shirt', 'Motorcortex T-Shirt',
    'Somatosensorycortex T-Shirt', 'Visualcortex T-Shirt',
    'Auditorycortex T-Shirt', 'Olfactorycortex T-Shirt',
    'Gustatorycortex T-Shirt', 'Insularcortex T-Shirt',
    'Cingulatecortex T-Shirt', 'Entorhinalcortex T-Shirt',
    'Perirhinalcortex T-Shirt', 'Parahippocampalcortex T-Shirt',
    'Retrosplenialcortex T-Shirt', 'Posteriorcingulatecortex T-Shirt',
    'Precuneuscortex T-Shirt', 'Supplementarymotorareacortex T-Shirt',
    'Premotorcortex T-Shirt',
    'Frontaleye fieldcortex T-Shirt', 'Parietaleye fieldcortex T-Shirt',
    'Supplementaryareacortex T-Shirt', 'Brocaareacortex T-Shirt',
    'Wernickeareacortex T-Shirt', 'Angular gyruscortex T-Shirt',
    'Supramarginal gyruscortex T-Shirt', 'Inferior parietal lobulecortex T-Shirt',
    'Superior parietal lobulecortex T-Shirt', 'Intraparietal sulcuscortex T-Shirt',
    'Lateral intraparietal areacortex T-Shirt', 'Ventral intraparietal areacortex T-Shirt',
    'Medial intraparietal areacortex T-Shirt', 'Anterior intraparietal areacortex T-Shirt',
    'Caudal intraparietal areacortex T-Shirt',
    'ZIP', 'Waistcoat', 'Mask', 'Balaclava', 'Suit',
    'Football', 'Jersey',
    'Sweatshirt',
]

def extract_brand(name):
    """Extract brand from product name like 'Stone Island Sweater' -> 'Stone Island'"""
    name = name.replace('\n', ' ').strip()
    
    # Try matching from the end - find the longest product type match
    for pt in sorted(PRODUCT_TYPES, key=len, reverse=True):
        # Check if name ends with product type
        if name.endswith(pt):
            brand = name[:len(name)-len(pt)].strip().rstrip(' -')
            if brand:
                return brand
        # Check for " Brand ProductType" pattern
        pattern = r'\s+' + re.escape(pt) + r'\s*$'
        m = re.search(pattern, name, re.IGNORECASE)
        if m:
            brand = name[:m.start()].strip().rstrip(' -')
            if brand:
                return brand
    
    # If no match, try splitting on common separators
    # Some names might be just brand names
    return name

# Read clothing.csv
with open('d:/fansbuy/finsbuy-main/category_csv/clothing.csv', 'r', encoding='utf-8-sig') as f:
    reader = csv.reader(f)
    header = next(reader)
    rows = list(reader)

# Extract brands and update
updated = 0
for row in rows:
    if len(row) >= 8 and not row[7].strip():
        name = row[0]
        brand = extract_brand(name)
        row[7] = brand
        updated += 1

# Write back
with open('d:/fansbuy/finsbuy-main/category_csv/clothing.csv', 'w', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(rows)

print(f"Updated {updated} rows with extracted brands")

# Show brand distribution
from collections import Counter
brands = Counter()
for row in rows:
    if len(row) >= 8:
        b = row[7].strip()
        if b:
            brands[b] += 1

print(f"\nTop 30 brands in clothing.csv:")
for brand, count in brands.most_common(30):
    print(f"  {brand}: {count}")
print(f"\nTotal unique brands: {len(brands)}")
